name: WerdBuilding
version: '${project.version}'
main: egordjae.werdbuilding.WerdBuilding
api-version: '1.20'
depend: [Towny]
commands:
  regbuild:
    usage: /<command> [menu]
  verdbuild:
    usage: /<command> [accept|denied|showmystat|showourstat]